In [2]:
import matplotlib.pyplot as plt
import numpy as np
import my_csvTools  
from mpl_toolkits.mplot3d import Axes3D

# 1. read 3D G.T.box from CSV



In [7]:
gt_dir = r"C:\Users\BB\Desktop\training_data\annotation_validate.csv"
gts = my_csvTools.readCSV(gt_dir)
gt_size = np.array([gt[4:7] for gt in gts[1:]]).astype(float)
print(gt_size)

[[16. 15.  4.]
 [ 5.  5.  4.]
 [ 5.  7.  4.]
 ...
 [ 4.  4.  4.]
 [ 6.  7.  6.]
 [ 5.  7.  4.]]


# 2. Calculate the distribution of anchor scale

In [8]:
norm_gt_size=[]
# [0.25,0.5,0.75,1,1.25,1.5,1.75,2]
ratio_title = [0.25,0.5,0.75,1,1.25,1.5,1.75,2,2]
h_diff_ratio=[[],[]]
for gt in gt_size:
    gt = gt/gt[0]
    for i ,ratio in enumerate(ratio_title):
        if gt[1] < (ratio[i]+ratio[i+1])/2:           
            norm_gt_size.append(gt)
            break
    gt = gt/gt[0]
    norm_gt_size.append(gt)

norm_gt_size = np.array(norm_gt_size)
print(norm_gt_size)
# # 繪製散點圖
# plt.scatter(h_data, d_data,s=10)
# plt.xlabel('h')
# plt.ylabel('d')
# plt.title(' h vs d distribution')
# plt.grid(True)
# plt.show()

[[1.         0.9375     0.25      ]
 [1.         1.         0.8       ]
 [1.         1.4        0.8       ]
 ...
 [1.         1.         1.        ]
 [1.         1.16666667 1.        ]
 [1.         1.4        0.8       ]]


In [14]:
h_diff_ratio = np.zeros((2, 0))
h_diff_ratio.append(1)
h_diff_ratio.append(2)
print(h_diff_ratio)   

AttributeError: 'numpy.ndarray' object has no attribute 'append'